[build]
builder = "NIXPACKS"

[deploy]
startCommand = "streamlit run demo.py --server.port $PORT --server.address 0.0.0.0"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
